- import_playbook: mapr-include-vars.yml
- name: Apply common configuration to all nodes
  hosts: common
  roles:
    - ../roles/common-prereq
#    - ../roles/common-selinux
    - {role: ../roles/common-oraclejdk18, when: jdk == 'oraclejdk18'}
    - {role: ../roles/common-openjdk18, when: jdk == 'openjdk18'}
    - {role: ../roles/common-mapruser, when: mapr_create_user}
    - ../roles/common-rpcbind
    - ../roles/common-ntp
    - ../roles/common-misc
    - ../roles/common-sysctl